### ISSUE TITLE
add_menu_page() should be allowed

### ISSUE THREAD

**Issue by manake** [envato/envato-theme-check#12]
There exist the following errors:
```
REQUIRED: Themes should use add_theme_page() for adding admin pages.
Line 15: add_menu_page(

REQUIRED: Themes should use add_theme_page() for adding admin pages.
Line 26: add_submenu_page(
Line 32: add_submenu_page(
```

but `add_theme_page()` adds menu items under "Appearance" menu only which is usually not desirable as theme options are usually a mix of "appearance" options and other options.

**Suggested fix:**
Remove this requirement altogether. (If not, then this would qualify for `info` label rather than `recommended` or `required`.)

**Comment by scottparry** [comment]
Removed this check.
