### ISSUE TITLE
Customizer Check

### ISSUE THREAD

**Issue by stefanwebicon** [envato/envato-theme-check#16]
Hi. I have a problem on theme check. It throws me the following error: "Found a Customizer setting that did not have a sanitization callback function. Every call to the add_setting() method needs to have a sanitization callback function passed.". I use the following framework to work with Customizer API (https://github.com/smartcatdev/Acid-WordPress-Customizer-Framework). The error is triggered on the line 124 on this file https://github.com/smartcatdev/Acid-WordPress-Customizer-Framework/blob/master/includes/AcidOption.php because the theme check searches for "sanitize_callback" array key and value, and this framework loads automatically this array item when a customizer control is rendered. Thank you.

**Comment by scottparry** [comment]
This isn't an issue with Theme Check. We cannot test for every possible implementation. Leave a note with your submission and the reviewer will check.
