### ISSUE TITLE
Consider adding check for parentheses and print?

### ISSUE THREAD

**Issue by cudazi** [envato/envato-theme-check#17]
Example, https://regex101.com/r/h1nGBI/1 checks for echo, print and either surrounding the variable using () with or without spaces.

https://github.com/envato/envato-theme-check/blob/d37a2c2a6a45d5b4d1fc7bbd671de3ca645e0c81/checks/themeforest.php#L54

**Comment by scottparry** [comment]
@cudazi I'll look into it. It was originally like this, but I can't remember why we changed it...

**Comment by scottparry** [comment]
That regex creates a ton of false positives (maybe why we originally changed). Check out this from TwentySixteen: https://envato.d.pr/AmyrW3

**Comment by cudazi** [comment]
Looks like I missed requiring a $ in that example, here's an update https://regex101.com/r/h1nGBI/2

**Comment by RiteshSaxena** [comment]
"echo  $" (double space) also clears the warning, consider that case as well...

**Comment by scottparry** [comment]
Pushed 32e0e6f87e1f569278af595b1c0403f93adf352c
