### ISSUE TITLE
Theme supports

### ISSUE THREAD

**Issue by themexcode** [envato/envato-theme-check#19]
Hi,

I add theme supports using an array, to avoid duplicating add_theme_support(... function. Plugin doesn't recognize this, it searches for add_theme_support('exact name') instead, so this code is not recognized:

```
$supports=array('automatic-feed-links', 'post-thumbnails');

foreach($supports as $support) {
    add_theme_support($support);
}
```

It would be great if it just searched for "automatic-feed-links" and "title-tag" strings in the whole theme code, in the same way as it does for "comment-reply" string instead of searching for wp_enqueue_script('comment-reply').

**Comment by scottparry** [comment]
This isn't a bug, this is just specific to the way you code your theme. We may look at this an enhancement for the future.

**Comment by scottparry** [comment]
What happens when the call contains an array of its own? `add_theme_support( 'post-formats', array( 'aside', 'gallery' ) );`

**Comment by scottparry** [comment]
If you'd like to send a pull request, I'll test it out.
