### ISSUE TITLE
Ternary operators ?: warning

### ISSUE THREAD

**Issue by nk-o** [envato/envato-theme-check#21]
We got warning on lines like these:

```php
echo $check ? 'yep' : 'nope';
echo ( $check ? 'yep' : 'nope' );
...
```

`
WARNING: Found echo ($ in the file ... Possible data validation issues found. All dynamic data must be correctly escaped for the context where it is rendered.
`

**Comment by scottparry** [comment]
Reviewers check the actual context of data validation coming from echo statements, that's why it is set as a WARNING rather than a REQUIRED.

**Comment by nk-o** [comment]
Some of the reviewers don't check this. They just see that there is a lot of warnings and make soft reject. There are a small number of good reviewers that know what they do.

This is a bug, why you closed the issue? Please, improve the regular expression.

**Comment by scottparry** [comment]
This isn't a bug. 

The RegEx is fine, it is picking up echo $check as it should. That's why reviewers check the context. 

If you find yourself being rejected, simply leave an explanation of the code in the Notes to Reviewer box in your submission.
