### ISSUE TITLE
Escaped translation strings

### ISSUE THREAD

**Issue by stefanwebicon** [envato/envato-theme-check#23]
Hi, I have a little problem. I get this: "All translatable strings must be escaped to prevent malicious code injection from a translation.", even if I use esc_html__(), esc_html_e(), esc_attr__() or esc_html( __() ). How should I escape them correctly?

Screenshot: https://prnt.sc/k9vb4c

**Comment by scottparry** [comment]
This change has been reverted for now as it's causing too many false positives.
