### ISSUE TITLE
Found add_meta_boxes in the theme.

### ISSUE THREAD

**Issue by Varinders0hal** [envato/envato-theme-check#24]
WARNING: Found add_meta_box in the file framework/page-options/general.php. Custom meta box functions are allowed for design only. Ensure this is a valid use case. 

Get this warning after check my theme using envato theme check plugin. but i can not resolve this issue .Please tell me about this warning and help me to resolve.

**Comment by scottparry** [comment]
Meta boxes are for design related content only. This is a WARNING that reviewers will check and provide feedback if needed. If your metaboxes are design only, you do not need to do anything.
