### ISSUE TITLE
echo $output; WPBakery templates

### ISSUE THREAD

**Issue by Ninetheme** [envato/envato-theme-check#26]
WARNING: Found echo $ in the file vc_templates/vc_custom_heading.php. Possible data validation issues found. All dynamic data must be correctly escaped for the context where it is rendered.
Line 77: echo $output;

Escaping is needed in functions and vc_templates files? These are not theme files but including theme folders.

Thanks

**Comment by scottparry** [comment]
Reviewers will manually check any WARNINGS and provide feedback if needed.

**Comment by Ninetheme** [comment]
Hi

Reviewers not approved these and [this](https://github.com/envato/envato-theme-check/issues/31)

**Comment by luisvelazquez** [comment]
Hi @Ninetheme 

Did you find a solution or your theme got accepted with those warnings?

**Comment by Ninetheme** [comment]
hi @luisvelazquez

You can use wp_kses or remove these files when you submit theme. Reviewers know this issue for now

**Comment by wpexplorer** [comment]
If you sanitized all the content within the shortcode you should suffix it with _escaped as per the Envato rules and comment it out.

`echo $output_escaped // variables within $output have already been escaped`
