### ISSUE TITLE
How do I use this? Not available in the plugin directory of WordPress.

### ISSUE THREAD

**Issue by gdebojyoti** [envato/envato-theme-check#27]
This may be a silly question. However, I cannot find a way to install and use Envato Theme Check.

I searched for Envato theme check in the WordPress plugin directory. Could not find an entry for it.

The readme section in the GitHub repo did not contain any details either.

How do I do this? I only have the default "Theme Check" from WordPress installed at the moment. I am not sure what else to do? Please help.

**Comment by scottparry** [comment]
Download the Master and install it as you would any plugin: https://github.com/envato/envato-theme-check/archive/master.zip
