### ISSUE TITLE
False positive for Found mail(

### ISSUE THREAD

**Issue by webbudesign** [envato/envato-theme-check#33]
![screen shot 2018-12-11 at 12 45 58 am](https://user-images.githubusercontent.com/5365445/49763605-3bbd4880-fcde-11e8-8087-623633c9eaae.png)

Hello, plugin giving a false error on text and sanitize_email function.

**Comment by webbudesign** [comment]
Also, I found one more false positive on Email word. Here is screenshot:
![screen shot 2018-12-11 at 12 58 11 am](https://user-images.githubusercontent.com/5365445/49764255-f39f2580-fcdf-11e8-8e41-d0df4725363c.png)

**Comment by scottparry** [comment]
I'll have a look into this. Having said that, all that looks like plugin territory functionality anyway.

**Comment by webbudesign** [comment]
Ok but setEmail is not about email function of WordPress. It is a function name. For example, if I use a function name with **letsdoemail(something)** system will give an error and this is false positive.

**Comment by scottparry** [comment]
Yeah, I see that. Will look into the cause.
