### ISSUE TITLE
"file_get_contents" needed for WordPress installation using FTP

### ISSUE THREAD

**Issue by cnhk** [envato/envato-theme-check#35]
`$wp_filesystem` should not be used for every single bit of file operation.

For writing it's definitely OK but when the file system method isn't "direct" ( like when using FTP ), getting the content of a file ( loading a list of Google Web Font and all the variants from a `.json` file in the dashboard for instance ) using `$wp_filesystem->get_contents()` will not work unless you ask the hostname/username/password ( show the WP's file system form ) for every single page load that relies on the content of a file even if there is no need to modify it.

This also makes reading the content of a file impossible when a page of the front end is viewed by an anonymous visitor ( still on an installation using FTP ).

**Comment by scottparry** [comment]
This is more of an issue with the actual requirements than the plugin itself.
