### ISSUE TITLE
Multiple Domain Found Issue 

### ISSUE THREAD

**Issue by sungraiz** [envato/envato-theme-check#37]
Hi,
     There is a bug in the plugin. When it checks the domains then the **array_unique** function just remove the duplicate values, not the empty ones. So, it is causing the issue and displaying the false warning.  Here is the full array before the **array_unique** plugin applied.  https://jmp.sh/4oMlQx5 So, please add a check which also removes the empty values.  You can use **array_filter** after  **array_unique** as i implemented here https://jmp.sh/VZTJNLA
Thanks

**Comment by scottparry** [comment]
1d517cb4631e7183937218caaa3e7754b3f381d6
