### ISSUE TITLE
Ignore .git folder

### ISSUE THREAD

**Issue by wpexplorer** [envato/envato-theme-check#40]
A lot of developers use Github for theme development and oftentimes the git folder prevents the theme check from running due to memory limit issues. Would be good to have a list of excluded folders that aren't checked and with a filter we can hook into if we want to include sass folders and anything else that is removed when we run our gulp build.

Thanks!

**Comment by wpexplorer** [comment]
Bump.

**Comment by emiluzelac** [comment]
@scottparry :)

**Comment by scottparry** [comment]
No idea how I missed this! Didn't get a notification! 

I'll look into this as soon as time permits. If you'd like to hurry it along, you could submit a pull request to get the ball rolling.

**Comment by wpexplorer** [comment]
@scottparry I actually have a few fixes and suggestions. Is there any Envato badge for helping with plugin development? ;)

**Comment by scottparry** [comment]
> @scottparry I actually have a few fixes and suggestions. Is there any Envato badge for helping with plugin development? ;)

Haha, I have no idea about getting a badge :D

**Comment by andyjdavis** [comment]
This and https://github.com/envato/envato-theme-check/issues/56 could presumably be done at the same time.

**Comment by scottparry** [comment]
Hidden files / folders should not be present in the final theme anyway so this is a mute point. Run themecheck after development, not during.

**Comment by andyjdavis** [comment]
I've put up a potential solution for this. See https://github.com/envato/envato-theme-check/pull/68
