### ISSUE TITLE
It can be useful if a verification method is integrated to check only unsafe and/or unreliable global variable

### ISSUE THREAD

**Issue by potenzatk** [envato/envato-theme-check#43]
Hello,

Please provide detail information about how we can remove this error with theme check and WPCS 

- It can be useful if a verification method is integrated to check only unsafe and/or unreliable global variables.

**WARNING**: Found $_SERVER in the file base-functions.php. PHP Global Variable found. Ensure the context is safe and reliable.
Line 693: $protocol = ( ! empty( $_SERVER['HTTPS'] ) && 'off' !== $_SERVER['HTTPS'] || isset( $_SERVER['SERV

https://i.imgur.com/lmEKnSm.png

Thanks

**Comment by scottparry** [comment]
WARNINGS will be checked by the reviewer and they will provide feedback if needed.
