### ISSUE TITLE
admin_bar_menu replacement?

### ISSUE THREAD

**Issue by anteksiler** [envato/envato-theme-check#45]
Like 99% of the themes, we use admin_bar_menu to add a menu for theme related pages and theme options.

If we cannot use it, what is the alternative?

**Comment by scottparry** [comment]
Themes should not any anything to the admin bar. If every theme / plugin did this, it would soon be pretty messy.

**Comment by BackuPs** [comment]
@scottparry  If every theme does this.....  How many themes can one have active at one time? The guy asks how he can add items to the admin bar? And he gets the most stupidest answer on the planet as a reply. You just won that price !

**Comment by scottparry** [comment]
> @scottparry If every theme does this..... How many themes can one have active at one time? The guy asks how he can add items to the admin bar to get past the idiot envato theme check plugin ! And he gets the most stupidest answer on the planet as a reply. You just won that price ! Why the .... do you think that action exists in wordpress? Why do you think the wp_admin_bar even has these hooks and functions? https://developer.wordpress.org/reference/classes/wp_admin_bar/add_menu/
> 
> And then some idiot at envato decides it is not theme territory?

If every THEME / PLUGIN. That's the key. 1 theme, 10 plugins, the admin bar gets cluttered fast.

**Comment by BackuPs** [comment]
Who is responsible for that? Envato? So the theme has to move that code into a plugin in order to work around the Envato Idiot Themecheck plugin ?   The same cluttered will happen !

This is utterly Stupid!

**Comment by scottparry** [comment]
> Who is responsible for that? Envato? So the theme has to move that code into a plugin in order to work around the Envato Idiot Themecheck plugin ? The same cluttered will happen !
> 
> This is utterly Stupid!

Yes it's an Envato requirement.
