### ISSUE TITLE
Pass Theme Check plugin but not pass Envato Theme Check plugin

### ISSUE THREAD

**Issue by anhdq1801** [envato/envato-theme-check#49]
Our theme published over 2 years on ThemeForest and now we submit update version. We check with plugin Theme Check (latest version release 4 week ago) it work well no Waring and no RECOMMENDED https://prnt.sc/oy5u1n but your review team just reject our theme update version with so much error https://envato.d.pr/lljD7e
I see your plugin last commit version since 7 months ago. Could you please update your plugin follow new version of plugin https://wordpress.org/plugins/theme-check/

Thanks

**Comment by scottparry** [comment]
Sorry, but the Envato Theme Check plugin is a fork of the original Theme Check plugin, which has been modified to more closely match Envato requirements. 

Your theme must pass Envato Theme Check plugin, not the WordPress Theme Check plugin.

**Comment by Stephen-Cronin** [comment]
Also, note this from the requirements:

>You must not rename the original class-tgm-plugin-activation.php file to anything else. You will receive false positives when running the Envato Theme Check plugin if you do this.

It looks to me like you might have renamed it to class-tgmpa.php which would explain some of your errors. Changing the name back will remove those, although there will still be others to fix.
