### ISSUE TITLE
Ignore node_modules & vendor folders

### ISSUE THREAD

**Issue by anteksiler** [envato/envato-theme-check#56]
Using Node & Composer for WPCS, these folders are included in the theme check. They should be ignore imho.

**Comment by growthwp** [comment]
I can't stress this enough, we just ran our first release candidate theme through the check, only to be prompted with a ton of errors that weren't even ours OR valid to begin with, most of the JS world's `node_modules` folders aren't even what's being shipped.

**Comment by drinkmaker** [comment]
I think the theme should be delivered to the end-user without `node_modules `, compiled and ready to use. Therefore, everything works correctly. Check the theme after the final build of all dependencies.

**Comment by scottparry** [comment]
I'd have to agree with @drinkmaker. The theme shouldn't be shipped with node_modules. Run themecheck after building.
