### ISSUE TITLE
Get an permanent error with php 7.4 - implode(): Passing glue string after array is deprecated. Swap the parameters

### ISSUE THREAD

**Issue by kamilionare12** [envato/envato-theme-check#57]
Plugin case those errors in PHP 7.4.8 (maybe newer)
Theme testing result: REQUIRED: error_log PHP error log found.
-
error log:

Deprecated | implode(): Passing glue string after array is deprecated. Swap the parameters | wp-content/plugins/envato-theme-check-master/checks/filenames.php:43

Deprecated | implode(): Passing glue string after array is deprecated. Swap the parameters | wp-content/plugins/envato-theme-check-master/main.php:58

Warning (Suppressed) | opendir(/home/p316069/www/adkox.com/wp-content/plugins/Envato-Theme-Check): failed to open dir: No such file or directory | wp-admin/includes/plugin.php:296

-
Can please fix it?

**Comment by scottparry** [comment]
If this is shown in Theme Check: REQUIRED: error_log PHP error log found. It's telling you to remove error_log from your theme directory.
