### ISSUE TITLE
The plugin do not check theme CORE plugin

### ISSUE THREAD

**Issue by kraftstudio** [envato/envato-theme-check#58]
Hello,
what about if my theme use CORE PLUGIN with framework and all core theme features was implemented in framework plugin, but not in the theme.
For example I have an error: REQUIRED: Could not find comment_form
But in fact framework plugin use comment_form and theme use framework plugin for render it.

How can I resolve the issue?

**Comment by scottparry** [comment]
That would be fine, simply explain to the reviewer.
