### ISSUE TITLE
false positive on mkdir

### ISSUE THREAD

**Issue by BackuPs** [envato/envato-theme-check#59]
Hi Guys,

What is wrong about using  $wp_filesystem->mkdir ?  I get a false positive on that and the advice to use wp_mkdir_p()  but that does not have the ability to parse $chmod (The permissions as octal number)  which i need to create a directory and set the permissions!  It is definitely not php mkdir ! It is from wordpress filesystem. It can't be wrong on using that.

Please advice !

![afbeelding](https://user-images.githubusercontent.com/6078370/95058247-8c920280-06f7-11eb-845c-be8fd807a915.png)

**Comment by scottparry** [comment]
You can ignore false positives. $wp_filesystem->mkdir is fine.
