### ISSUE TITLE
cli - Text domain always fails

### ISSUE THREAD

**Issue by AaronRutley** [envato/envato-theme-check#6]
As reported by @Stephen-Cronin on Slack
> If I run Theme Check via wp cli on Twenty Seventeen, it fails on the text domain with the `This theme's correct slug and text-domain is .` message. If I run it via the WP backend it's fine

**Comment by egyflad** [comment]
I am getting to lose my mind on this :( 
the checker gives me this message: "WARNING: Found a translation function that is missing a text-domain. Function _e, with the arguments 'theme-text-domain'

*theme-text-domain is for my text domain!

I have checked each file in my theme and there so no such a problem, Please advice on this.

Here is a screen shot: 
http://prntscr.com/kbktdz

Regards,

**Comment by scottparry** [comment]
@egyflad Is this via WP Admin or CLi? Also, we'd need to see the actual code.

**Comment by egyflad** [comment]
@scottparry 
Thanks for your response I really appreciate it. 
This via WP admin while using the Envato Check Plugin. 

there is no code, it's just the error message:
http://prntscr.com/kbktdz

if this would help: 
I use the function like so: 
<?php _e('Previous Post', 'text-domain') ?>

*Again text-domain is for my theme name I just can't type it here publicly !

Regards,

**Comment by scottparry** [comment]
@egyflad The only real way for me to test this would be to have access to the theme so I can run checks. 

Seeing as this isn't related to CLi, if you want to try fixing, please open a new Issue so it's seperated from this.
