### ISSUE TITLE
textdomain check missing file name

### ISSUE THREAD

**Issue by BackuPs** [envato/envato-theme-check#60]
Please change the text domain check php so we get information about the file where a issue has been found. See image. otherwise one has to spend hours of searching for the correct file !

![afbeelding](https://user-images.githubusercontent.com/6078370/95058485-e692c800-06f7-11eb-9664-b0de3664ca4b.png)

**Comment by scottparry** [comment]
https://github.com/envato/envato-theme-check/commit/6fd28ae1743f364881de6f69c9074a6a8e24c7e3
