### ISSUE TITLE
Filesystem API requirement should exclude file_get_contents

### ISSUE THREAD

**Issue by andrejcremoznik** [envato/envato-theme-check#63]
The Filesystem API should be used for write operations.

> Any theme or plugin that needs to write files locally should do so using the WP_Filesystem family of classes.

As stated on https://developer.wordpress.org/apis/handbook/filesystem/ .

**The problem**

I only need to read a file's contents. By calling `WP_Filesystem()` the method returned will resolve to `ftpsocket` if the filesystem isn't directly writeable by the PHP process. `ftpsocket` cannot be used without calling for `request_filesystem_credentials`.

This makes no sense. I only need to read a read-only file. I do not want to ask the user for any FS credentials because I do not need write permissions. The end result is that I'm annoying users with bad UX at best or introducing security holes at worst if the user feels like making the installation writeable by PHP.

**The solution**

Exclude `file_get_contents` from the checks.

**Comment by scottparry** [comment]
This check is for security too not just filesystem usage and the reviewer will determine the usage during review.

**Comment by andrejcremoznik** [comment]
Then drop the severity from "REQUIRED" to "WARNING". I guarantee you not a single one of the reviewers I've interacted with will look at the code. Why? Because I'm left with fixing a bunch of legacy themes written by amateurs (e.g. WP professionals) and I can tell you that the amount of security issues not or falsely identified by this plugin is laughable.
