### ISSUE TITLE
Empty alt attribute on an image is a VALID use case

### ISSUE THREAD

**Issue by andrejcremoznik** [envato/envato-theme-check#66]
Copy-paste from MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img

> Omitting alt altogether indicates that the image is a key part of the content and no textual equivalent is available. **Setting this attribute to an empty string (alt="") indicates that this image is not a key part of the content (it’s decoration or a tracking pixel), and that non-visual browsers may omit it from rendering.** Visual browsers will also hide the broken image icon if the alt is empty and the image failed to display.

Empty alt `alt=""` is currently marked as a `REQUIRED` item to fix. This in unacceptable.

**Comment by scottparry** [comment]
https://github.com/envato/envato-theme-check/commit/d8cff343c84d66d8cda8b6e16cf47cd4442774b8
