### ISSUE TITLE
The `is_plugin_active` check probably needs to be a Warning or Info only

### ISSUE THREAD

**Issue by Stephen-Cronin** [envato/envato-theme-check#7]
@iKreativ I just got pinged on [this TGM PA issue](https://github.com/TGMPA/TGM-Plugin-Activation/issues/737)

In the context of TGM PA, using `is_plugin_active` does make sense, so this should probably be an Info or Warning rather than Required. Then the Reviewer can check if it's TGM PA or not.

**Comment by iKreativ** [comment]
Yeah. I'm actually going to have a look at excluding TGM from this check to correct the false positive. If not, I'll switch to WARNING.

**Comment by Stephen-Cronin** [comment]
Thanks. That would be cool if we could do it!

**Comment by iKreativ** [comment]
Fixed in https://github.com/envato/envato-theme-check/commit/5ce47c277b30f170c9a1f4d5b7ffd993f2c493c9
