### ISSUE TITLE
WPAdminBar notifications do not show the file as the %1$s is missing in the code.

### ISSUE THREAD

**Issue by BackuPs** [envato/envato-theme-check#72]
WPAdminBar notifications do not show the file as the %1$s is missing in the code.

Please adjust the file accordingly code below so we know what file the themecheck plugin is refering to.

`

			$this->error[] = sprintf( '<span class="tc-lead tc-required">' . __( 'REQUIRED', 'theme-check').'</span>: ' . __( 'You are not allowed to hide the admin bar. File : %1$s', 'theme-check' ), 
									'<strong>' . $filename . '</strong>');	

			$this->error[] = sprintf( '<span class="tc-lead tc-warning">' . __( 'WARNING', 'theme-check').'</span>: ' . __( 'The theme is using `#wpadminbar`. Hiding the admin bar is not allowed. File : %1$s', 'theme-check' ), 
									'<strong>' . $filename . '</strong>');		

`

I attached the file with the modifications already made

[adminbar.zip](https://github.com/envato/envato-theme-check/files/14371053/adminbar.zip)

Thank you

**Comment by scottparry** [comment]
https://github.com/envato/envato-theme-check/commit/dcb824f79223f6ab1cbc2f44a75097f0d712f334
