### ISSUE TITLE
Checking for the presence of iframe, site_url, wp_title, etc. in the code is often not correct

### ISSUE THREAD

**Issue by VadymPogorelov** [envato/envato-theme-check#74]
Installed the latest version of Envato Theme Check 2.0.0 plugin https://prnt.sc/PmnEW2nHu8Nj to check themes.

There are many new INFOs and WARNINGs, most of which do not work correctly. Here are some examples:

1) Checking for the presence of <iframe> tag in the code “catches” all occurrences of this substring - in function or variable names, inside text strings and regular expressions https://prnt.sc/C2y-coFyVQZQ Although in reality the html tag <iframe> is not inserted anywhere in the code, but simply analyzes the page output for its presence (mainly detecting embedded video, audio, etc.)

2) The same with the 'site_url' line https://prnt.sc/VcmiEBYZgXFv, which for some reason is perceived as using the site_url() function https://prnt.sc/j4aw5zbGl78K.

3) Same with 'wp_title': https://prnt.sc/i7MXgFKpIOnI
And actually there are 4 occurrences of the 'wp_title' substring in the code:
https://prnt.sc/u_3QLaVN4EF3 and https://prnt.sc/fbF8Uh_QVMwd

4) Here in general it reacts to a part of the filter name as a function call https://prnt.sc/t61HV0xfipya.

5) Sometimes it finds even something that does not exist in the file:
https://prnt.sc/j-Af_rxn0mDt
https://prnt.sc/-YcltqT0JEQw

6) Warns about the need to use one domain when it is already one https://prnt.sc/Gxp-eQ8IHqeX

It is not difficult to distinguish a function call from a string or variable name in code. So why these remarks for the sake of remarks?

**Comment by scottparry** [comment]
They are INFO checks, some of which are from the official theme check plugin that reviewers check during the review process.
