### ISSUE TITLE
Improve Theme Check Plugin to Detect Custom Post Type Registration via register_post_type()

### ISSUE THREAD

**Issue by femkhan** [envato/envato-theme-check#75]
Currently, the Theme Check plugin flags any instance of "posttype" as indicating plugin territory. However, this often leads to false positives for meta fields, CSS class names, or other legitimate uses within themes. To address this issue, I propose modifying the check to specifically target the function register_post_type(), which is the primary method for registering custom post types.

**Regex Update: Change from '/posttype/' to the below code.**

`'/register_post_type\s?\(/' => esc_html__( 'Custom post types should be registered via a plugin, not within a theme', 'theme-check' ),
`

This change will ensure that the warning only appears when a theme registers a custom post type directly, which indeed should be managed via a plugin. Better compatibility for existing themes with meta fields, class names, or other identifiers using "posttype."

**Comment by scottparry** [comment]
This detects correctly for what is required. Meta fields are plugin territory therefore it needs to detect them. Reviewers manually check to ensure false positives are not rejected.
