### ISSUE TITLE
Warning issues are in framework's code

### ISSUE THREAD

**Issue by nurulalam3s** [envato/envato-theme-check#8]
Some warning issues are in framework's code I think, these are secured. Without these we have a couple of issues like as $args ['before_widget'] & $args ['after_widget'] if we escape those then it's stopped working.

How to solve the framework & WP core variable warnings could you please provide any good solution?

**Comment by iKreativ** [comment]
If it is a WARNING reviewers will check and provide feedback. All REQUIRED notices need addressing.

Anything you bundle with your theme must follow the same standards as the theme itself.

**Comment by nurulalam3s** [comment]
That means I am able to submit the theme with WARNING, right?

**Comment by iKreativ** [comment]
Yes.

**Comment by nurulalam3s** [comment]
Thanks @iKreativ
