### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by muratdesign** [envato/envato-theme-check#9]
`WARNING: Found remove_filter( in the file theme-init.php. Themes should not remove core filters. Ensure this is a valid use case.
Line 243: remove_filter( 'the_excerpt', 'wpautop' );
Line 258: remove_filter( 'get_search_form', 'cursornt_header_search_form_new' );
WARNING: Found remove_filter( in the file tgm.php. Themes should not remove core filters. Ensure this is a valid use case.
Line 898: remove_filter( 'upgrader_source_selection', array( $this, 'maybe_adjust_sou
Line 2984: remove_filter( 'upgrader_source_selection', array( $this->tgmpa, 'maybe_adj
Line 3418: /* [TGMPA - ] remove_filter('upgrader_clear_destination', array($this, 'delete_old_plugin
Line 3421: remove_filter( 'upgrader_post_install', array( $this, 'auto_activate' ), 10
Line 3446: remove_filter( 'upgrader_post_install', array( $this, 'auto_activate' ), 10
WARNING: Found remove_filter( in the file aq_resizer.php. Themes should not remove core filters. Ensure this is a valid use case.
Line 118: if ( true === $upscale ) remove_filter( 'image_resize_dimensions', array( $this, 'aq_upscale' ) );
REQUIRED: Found is_plugin_active( in the file theme-init.php. is_plugin_active() is not reliable. Use function_exists() or class_exists() instead.
Line 532: if ( is_plugin_active('easy_installer/init.php') ) {
Line 540: if ( is_plugin_active('wordpress-importer/wordpress-importer.php') ) { ?>
REQUIRED: Found is_plugin_active( in the file tgm.php. is_plugin_active() is not reliable. Use function_exists() or class_exists() instead.
Line 905: if ( $this->is_automatic && ! $this->is_plugin_active( $slug ) ) {
Line 1065: } elseif ( $this->is_plugin_active( $slug ) ) {
Line 1126: if ( $this->is_plugin_active( $slug ) && false === $this->does_plugin_have_update( $slu
Line 1144: if ( ! $this->is_plugin_active( $slug ) && $this->can_plugin_activate( $slug ) ) {
Line 1800: if ( ! $this->is_plugin_active( $slug ) || false !== $this->does_plugin_have_update( $slu
Line 1831: public function is_plugin_active( $slug ) {
Line 1832: return ( ( ! empty( $this->plugins[ $slug ]['is_callable'] ) && is_callable( $this->plugins[ $slug ]['is_callable'] ) ) || is_plugin_active( $this->plugins[ $slug ]['file_path'] ) );
Line 1887: return ( ! $this->is_plugin_active( $slug ) && ! $this->does_plugin_require_update( $slug ) )
Line 2050: if ( true === $plugin['force_deactivation'] && is_plugin_active( $plugin['file_path'] ) ) {
Line 2316: if ( $this->tgmpa->is_plugin_active( $slug ) && false === $this->tgmpa->does_plugin_have_updat
Line 2407: if ( ! $this->tgmpa->is_plugin_active( $slug ) ) {
Line 3335: $maintenance = $maintenance || ( is_plugin_active( $plugin ) && isset( $current->response[ $plugin] ) );
Line 3364: $this->skin->plugin_active = is_plugin_active($plugin);
Line 3471: if ( ! is_plugin_active( $plugin_info ) ) {`

**Comment by muratdesign** [comment]
the is_plugin_active and remove_filter () errors are added but we have to use them


________________________________
Gönderen: Scott Parry <notifications@github.com>
Gönderildi: 25 Nisan 2018 Çarşamba 12:22
Kime: envato/envato-theme-check
Bilgi: Murat Güler; Author
Konu: Re: [envato/envato-theme-check] Errors (#9)


I don't understand, are you asking a question? This should only be used for opening relevant issues.

**Comment by scottparry** [comment]
remove_filter() is a WARNING only, reviewers will check if it is a valid use case. is_plugin_active() is REQUIRED.

Again, this isn't the place for asking questions. It should only be used for valid issues.

**Comment by muratdesign** [comment]
Sorry , Thank you.


________________________________
Gönderen: Scott Parry <notifications@github.com>
Gönderildi: 25 Nisan 2018 Çarşamba 12:29
Kime: envato/envato-theme-check
Bilgi: Murat Güler; Author
Konu: Re: [envato/envato-theme-check] Errors (#9)


remove_filter() is a WARNING only, reviewers will check if it is a valid use case. is_plugin_active() is REQUIRED.

Again, this isn't the place for asking questions. It should only be used for valid issues.

**Comment by scottparry** [comment]
You're welcome. When you submit your theme, reviewers will provided feedback on things like this, don't worry!

**Comment by muratdesign** [comment]
I understand, thanks


________________________________
Gönderen: Scott Parry <notifications@github.com>
Gönderildi: 25 Nisan 2018 Çarşamba 12:36
Kime: envato/envato-theme-check
Bilgi: Murat Güler; Author
Konu: Re: [envato/envato-theme-check] Errors (#9)


You're welcome. When you submit your theme, reviewers will provided feedback on things like this, don't worry!
